### ISSUE TITLE
Failure to use the simulator with tpm2-abrmd

### ISSUE THREAD

**Issue by giladbeeri** [tpm2-software/tpm2-abrmd#442]
Ubuntu 16.04 in a VirtualBox, installed without errors

tpm2-tss 1.4.0
tpm2-abrmd 1.3.1
tpm2-tools 3.0.4

and installed the simulator, running the simulator seems to work, but then:

```
user@pc:~/Downloads/ibmtpm974/src$ tpm2-abrmd --allow-root

** (tpm2-abrmd:29959): CRITICAL **: Failed to parse options: Unknown option --allow-root

user@pc:~/Downloads/ibmtpm974/src$ tpm2-abrmd 

** (tpm2-abrmd:29984): WARNING **: failed to initialize device TCTI context: 0xa000a

** (tpm2-abrmd:29984): CRITICAL **: TCTI initialization failed: 0xa000a

```

**Comment by martinezjavier** [comment]
@giladbeeri AFAIK the default TCTI for the tpm2-abrmd is `device`, but you want to use the `socket` one to communicate with the simulator:

```
$ tpm2-abrmd -t socket
```

The problem is that you are trying to access a real TPM device and either isn't present in your machine or your user doesn't have access. Also, you are using tpm2-abrmd 1.3.1 but this version doesn't have the `--allow-root` option.

**Comment by flihp** [comment]
answer from @martinezjavier LGTM. No response in almost a week so assuming issue is resolved. Please re-open if the issue persists.
