### ISSUE TITLE
CRITICAL **: failed to allocate dbus proxy object: Error calling StartServiceByName for com.intel.tss2.Tabrmd: Timeout was reached

### ISSUE THREAD

**Issue by jturnsek** [tpm2-software/tpm2-abrmd#541]
#include <errno.h>
#include <glib.h>
#include <inttypes.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "tss2-tcti-tabrmd.h"

#define CONNECTION_COUNT 2

TSS2_RC
tcti_tabrmd_init (TSS2_TCTI_CONTEXT **tcti_context,
                  const char         *conf,
                  int                 retries)
{
    TSS2_RC rc;
    size_t size, i;

    rc = Tss2_Tcti_Tabrmd_Init (NULL, &size, NULL);
    if (rc != TSS2_RC_SUCCESS) {
        fprintf (stderr, "Failed to get allocation size for tabrmd TCTI "
                 " context: 0x%" PRIx32 "\n", rc);
        return rc;
    }
    *tcti_context = calloc (1, size);
    if (*tcti_context == NULL) {
        fprintf (stderr, "Allocation for TCTI context failed: %s\n",
                 strerror (errno));
        return rc;
    }
    for (i = 0; i < (size_t) retries; ++i) {
        rc = Tss2_Tcti_Tabrmd_Init (*tcti_context, &size, conf);
        if (rc == TSS2_RC_SUCCESS) {
            break;
        } else {
            g_info ("Failed to initialize tabrmd TCTI context: 0x%" PRIx32
                    " on try %zd", rc, i);
            sleep (1);
        }
    }
    if (rc != TSS2_RC_SUCCESS) {
        fprintf (stderr, "Failed to initialize tabrmd TCTI context: "
                 "0x%" PRIx32 "\n", rc);
        free (*tcti_context);
    }
    return rc;
}

int
main (int   argc,
      char *argv[])
{
    pid_t childPID;
    TSS2_RC rc;
    TSS2_TCTI_CONTEXT *tcti_context[CONNECTION_COUNT] = { 0 };
    size_t i;
    
    rc = tcti_tabrmd_init (&tcti_context [0],
                           NULL,
                           3);
    if (tcti_context [0] == NULL || rc != TSS2_RC_SUCCESS) {
        g_error ("failed to connect to TCTI: 0x%" PRIx32, rc);
    }

    childPID = fork();

    rc = tcti_tabrmd_init (&tcti_context [1],
                           NULL,
                           3);
    if (tcti_context [1] == NULL || rc != TSS2_RC_SUCCESS) {
        g_error ("failed to connect to TCTI: 0x%" PRIx32, rc);
    }
    
    for (i = 0; i < CONNECTION_COUNT; ++i) {
        Tss2_Tcti_Finalize (tcti_context [i]);
        free (tcti_context [i]);
    }
}

_Originally posted by @jturnsek in https://github.com/tpm2-software/tpm2-abrmd/issues/529#issuecomment-424335134_

**Comment by flihp** [comment]
Thx for the test code. Will try to spend some cycles on this soon.

**Comment by jturnsek** [comment]
It looks like file descriptor leak. My test program does not actually call Tss2_Tcti_Finalize before forking. But even if I put Tss2_Tcti_Finalize  before forking, two anon_inode:[eventfd] file descriptors remained in the parent process, which in turn get forked also and I think (although I am not sure) this is the reason for failing next init function. This explains also the fact the forking before any Tss2_Tcti_Tabrmd_Init function call works, because there is no file descriptors dangling around. I wonder who is responsible for closing those file descriptors: tabrmd or glib-2.0.

**Comment by jturnsek** [comment]
I have not be able to locate the problem of leaking resources. I was debugging down to g_main_context opening some eventfd descriptors, but not releasing them in Tss2_Tcti_Finalize. It is quite difficult to debug through those macro ridden functions in glib on embedded platform with limited resources. If something is opened in Tss2_Tcti_Tabrmd_Init it must be released in Tss2_Tcti_Finalize. Am I right? Have you been able to reproduce problem on your platform? We are close to release, but we don't have a solution yet. Could you please help us here.

**Comment by jturnsek** [comment]
I have upgraded glib to version 2.58.0 and the problem is the same.

**Comment by jturnsek** [comment]
@flihp: Have you had chance to test my code snippet yet?

**Comment by flihp** [comment]
busy times, taking a look at this now

**Comment by flihp** [comment]
have a repro and a failing test case

**Comment by flihp** [comment]
My expectation is that the series of events:
1) create TCTI
2) fork
3) create TCTI in child

shouldn't produce an error in the child.

**Comment by flihp** [comment]
Did some experimenting this morning. Spent some quality time with dbus-monitor and didn't see anything weird. Connections are established with the expected messages exchanged. When the failure occurs no messages are sent so that rules out the daemon doing something stupid.

To pair down the possible causes I wrote up a small program to connect to the session bus and poke the well known DBus object that the `dbus-daemon` exposes there. To do this we can't use the code generated for tabrmd by `dbus-codegen` so we use `g_bus_get_sync` and `g_dbus_proxy_new_sync`. These are the same mechanisms used in the code generated by `dbus-codegen`. Code is here: [fork-proxy.txt](https://github.com/tpm2-software/tpm2-abrmd/files/2474502/fork-proxy.txt)

Interestingly enough this code exhibits the same behavior as the reference code provided and the tests I hacked up yesterday in #544. Since these are all straight glib functions I'm starting to think this may be the wrong way to create connections since it's clear `fork`ing messes something up in the child.

**Comment by jturnsek** [comment]
I have a suspicion that g_initable_init is opening DBusConnection and a context is saved somewhere locally. After a fork this same context is referenced because I see the refcount on the DBusConnection is increased. Ok, that maybe is the problem of glib itself, but I have tried a different test case, where I call tcti finalize function just before the fork and I would expect the function to clear everything so that next call to tcti initialize would call g_initable_init like for the first time, but this is not the case here.

**Comment by jturnsek** [comment]
Following statement from glib api description clearly states that singleton object is returned when calling g_bus_get_sync multiple times in a process and forking maybe falling into same category here. Could this be an issue here?

/**
 * g_bus_get_sync:
 * @bus_type: a #GBusType
 * @cancellable: (nullable): a #GCancellable or %NULL
 * @error: return location for error or %NULL
 *
 * Synchronously connects to the message bus specified by @bus_type.
 * Note that the returned object may shared with other callers,
 * e.g. if two separate parts of a process calls this function with
 * the same @bus_type, they will share the same object.
 *
 * This is a synchronous failable function. See g_bus_get() and
 * g_bus_get_finish() for the asynchronous version.
 *
 * The returned object is a singleton, that is, shared with other
 * callers of g_bus_get() and g_bus_get_sync() for @bus_type. In the
 * event that you need a private message bus connection, use
 * g_dbus_address_get_for_bus_sync() and
 * g_dbus_connection_new_for_address().
 *
 * Note that the returned #GDBusConnection object will (usually) have
 * the #GDBusConnection:exit-on-close property set to %TRUE.
 *
 * Returns: (transfer full): a #GDBusConnection or %NULL if @error is set.
 *     Free with g_object_unref().
 *
 * Since: 2.26
 */

**Comment by flihp** [comment]
I went down this rabbit hole on Friday. I saw the reference to the singleton and started looking @ the gio / dbus code and I think I came up with a way to create the context manually w/o interacting with the singleton. The code is attached. Problem is that it still causes the same error. Note that this is straight glib/gio code, nothing from tpm2-abrmd: [fork-proxy-connection-unique.int.c.gz](https://github.com/tpm2-software/tpm2-abrmd/files/2480355/fork-proxy-connection-unique.int.c.gz)

Not sure if I missed something but I think this code avoids the singleton mentioned in the docs by not using the `g_bus_get_sync` convenience function. Instead in manually:
1) gets the right address for the bus (hard coded to session bus)
2) creates the connection object
3) initialize the connection object using the initable interface (this is the part that fails since it connects to the bus)
4) creates a proxy object from the connection

I had hoped that step 3 would produce a few dbus messages to help with debugging but the call never gets out of gio and no messages (not even the typical connection 'Hello' message) shows up.

Now that we have some generic code (pure glib/gio) to trigger the failure it'll be a lot easer to get help from glib / gnome community. I'll try to get a question out to them soon but from the random searching I've been doing it looks as though `fork` without an `exec` call soon after is very much a corner case. Hopefully they won't just say "unsupported" :crossed_fingers:

In the event that I do get people saying "you shouldn't fork w/o execing immediately after" can you provide any additional data w/r/t the use case? Is this pattern strictly necessary? Any chance you think we might come up with a workaround in your code in the event this pattern isn't supported?

**Comment by jturnsek** [comment]
Our use case is quite normal (I think). We have an Apache 2.4.16 with mod_nss module enabled to communicate with our tpm2 HSM, which uses tabrmd. Forking of child processes is done by Apache itself with mpm worker. What I do not understand is why Apache (through mod_nss) calls C_Initiliazie API, some PKCS#11 API fuctions and then C_Finalize. After that it spawns child processes by calling fork and each child calls C_Initialize again. In the C_Initialize the tabrmd client is initialized and finalized in C_Finalize. This surely must be a bug in glib, because finalize fuctions should clear everything about DBus connection, but they obviously are not doing that completely.

**Comment by flihp** [comment]
Yeah I saw the mention of apache and figured it was part of the framework. Another option would be get rid of the glib stuff from the client side of this (TCTI) if we end up with no other option. I don't know how much work that would end up being but it's an option if all else fails.

**Comment by jturnsek** [comment]
If this issue will not be resolved, I do not know how anyone could use tabrmd with Apache and I do not mean this in a negative way. I was thinking about switching Apache with Nginx perhaps, but that would be to big risk for us now. Also have tried to switch mp worker to prefork, and nothing. I sure hope so it is an issue in glib itself (because of the corner case). Let see what glib guys have to say about it.

**Comment by flihp** [comment]
What kernel version is on your platform? Around 4.14 some basic context mgmt was added to the kernel. This is documented in our README here: https://github.com/tpm2-software/tpm2-abrmd/#tpm2-abrmd-vs-in-kernel-rm.

**Comment by jturnsek** [comment]
Succesfully backported tpm resource manager from latest Linux kernel. Will try to ditch tabrmd and work with rm.

**Comment by jturnsek** [comment]
Good news. RM from kernel is working like a charm.

**Comment by flihp** [comment]
Thanks for playing along and providing such detailed feedback. It looks like the only way to solve this problem for the tabrmd is to remove glib from the client library. That's a pretty heavy lift which has limited longterm value given that the goal is to have the kernel take over this role anyways. Glad you were able to backport the kernel patch as a workaround so quickly.

**Comment by daveman1010221** [comment]
Hey, all. I'm getting this exact error in September 2019 on Ubuntu. Any idea what causes this? A few details:

`Package: tpm2-tools                      
State: installed
Automatically installed: no
Version: 1.0.0+20160226.64b3334-0ubuntu2
Priority: optional
Section: universe/utils
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Uncompressed Size: 987 k
Depends: libc6 (>= 2.14), libcurl3 (>= 7.16.2), libssl1.0.0 (>= 1.0.0), libtss2-0, libtss2-utils
Description: TPM 2.0 utilities
 This package contains a set of tools to use with TPM 2.0 chips, for common tasks and features provided by the hardware; such as for doing basic key management, attestation, encryption and signing.
Homepage: https://github.com/01org/tpm2.0-tools
`

Error:
`sudo -u tss tpm2-abrmd                                                                                                                                                  8.1m  Wed 11 Sep 2019 04:49:04 PM EDT

** (process:9496): WARNING **: tcti_conf before: "device:/dev/tpm0"

** (tpm2-abrmd:9496): WARNING **: tcti_conf after: "device:/dev/tpm0"

** (tpm2-abrmd:9496): CRITICAL **: Failed to acquire DBus name com.intel.tss2.Tabrmd. UID 999 must be allowed to "own" this name. Check DBus config and check that this is running as user tss or root.
`

**Comment by keke8273** [comment]
I am having a the same problem with `nginx`. The environment is as follows:
```
kernel 5.3.0-61-generic
nginx 1.14
openssl 1.1.1
tpm2-tss-engine 1.1.0-rc0
tpm2-tss 2.4.1
tpm2-abrmd 2.3.1
```
Running `nginx` with the following openssl.conf allows the master process to query tpm

<pre>
openssl_conf = openssl_init

[openssl_init]
engines = engine_section
[engine_section]
tpm2tss = tpm2tss_section
[tpm2tss_section]
engine_id = tpm2tss
dynamic_path = /usr/lib/x86_64-linux-gnu/engines-1.1/libtpm2tss.so
default_algorithms = RSA
init = 1
<b>SET_TCTI = tabrmd:bus_name=com.intel.tss2.Tabrmd</b>
#SET_OWNERAUTH=owner123
#SET_PARENTAUTH =""

[req]
distinguished_name = subject

[subject]
</pre>
