### ISSUE TITLE
No man page for tpm2-abrmd.conf

### ISSUE THREAD

**Issue by yunyings** [tpm2-software/tpm2-abrmd#660]
During Fedora package Man Page scan, there's report about missing man page for tpm2-abrmd.conf:
https://bugzilla.redhat.com/show_bug.cgi?id=1612298

Is it possible to fix this from upstream?

**Comment by flihp** [comment]
Thanks @yunyings. I'll queue this up for a future release.

**Comment by flihp** [comment]
Took a quick pass over the bug report in the redhat bugzilla:

```
[ OK ] binary /usr/sbin/tpm2-abrmd has man page /usr/share/man/man8/tpm2-abrmd.8.gz
[ Warn ] man page is in section 8. Only commands requiring admin privileges, or daemons should be in this section, the rest should be in section 1
```
This warning can be ignored since `tpm2-abrmd` is a daemon and therefore belongs in section 8.

```
[ Error ] config file /etc/dbus-1/system.d/tpm2-abrmd.conf has no man page! Check it's content for proper documentation
```
This error is probably a false positive. This config file is used to populate dbus policy and is required to have the `.conf` suffix (otherwise dbus will ignore it). It should never be changed by the user. Can you provide an example package from redhat that creates such a file and has a man page for it?

```
[ Warn ] these (2) man pages left unassigned:
/usr/share/man/man3/Tss2_Tcti_Tabrmd_Init.3.gz
/usr/share/man/man7/tss2-tcti-tabrmd.7.gz
```
I don't know what this warning means. Please provide some context?

```
[ Warn ] found repeated words in man page: size 
```
This repetition is intentional and is clear from context.

Based on the above I don't believe any action is required. These all look like false positives, but I'm not sure how to handle the config file. Please provide more context / guidance?

**Comment by flihp** [comment]
By way of example: on my Ubuntu VM there's a pile of `*.conf` files under `/etc/dbus-1/system.d/` and none have man pages.

**Comment by flihp** [comment]
Added to the 2.3.1 milestone in case something comes of this thread.

**Comment by flihp** [comment]
no data -> closing as invalid
