### ISSUE TITLE
systemd auto-restart causing more problems than it solves

### ISSUE THREAD

**Issue by flihp** [tpm2-software/tpm2-abrmd#667]
Have had a few folks on Ubuntu reporting that `tpm2-abrmd` gets installed even though the platform doesn't have a TPM device (no /dev/tpm*).

- https://github.com/tpm2-software/tpm2-abrmd/issues/661
- https://github.com/tpm2-software/tpm2-tss/issues/1541
- https://www.reddit.com/r/linuxquestions/comments/dhinl0/what_is_tpm2abrmdservice_and_why_does_it_try_fail/

The systemd config we use will attempt to auto-restart the daemon if it dies but without a TPM device the daemon keeps dying and systemd keeps restarting it. This spams the hell out of users lots. The preferable approach would be to figure out a way to let systemd know when a failure is unrecoverable. Baring this I think the only viable solution would be to stop auto-restarting the daemon. Alternatively we could modify the daemon such that it will run even if there's no TPM device. It could instead run normally but return errors to users indicating that no TPM device is available.

**Comment by AndreasFuchsSIT** [comment]
How about
```
Restart=on-failure
SuccessExitStatus=72 77
```
(see https://www.freedesktop.org/software/systemd/man/systemd.service.html#Restart=)
and `exit(77)` if `/dev/tpm0` and `/dev/tpmrm0` are not available ?
72 as in EX_OSFILE and 77 for EX_NOPERM (see https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Process%20exit%20codes)

With the rational that the daemon-start call was a success but daemon-mainloop skipped due to missing dev/tpm0 file or permissions ?

**Comment by flihp** [comment]
Tanks for the pointers. I've got some time blocked later this week to work on this.
