### ISSUE TITLE
Service Start Issue for tpm2-abrmd

### ISSUE THREAD

**Issue by heobu** [tpm2-software/tpm2-abrmd#737]
Hello,

I have a TPM2.0 chip and have followed the guides on how to install tpm2-abrmd as a resource manager, but when I try to start it as a service, I am getting this error:

![image](https://user-images.githubusercontent.com/22464721/99046732-3d67a900-25a4-11eb-9b02-c56bb4dc6af3.png)

What could be the reason for this and how can I solve this?

I do have such a TPM device under dev:
![image](https://user-images.githubusercontent.com/22464721/99047384-34c3a280-25a5-11eb-826b-de5d0ed1a0c5.png)

Alternatively I do this:
`tpm_server &`
`sudo -u tss tpm2-abrmd --tcti=mssim &`

This seems to work fine but then I cannot execute any tpm2pkcss11-tool commands or anything without using sudo, so my resource manager is probably not working as expected? Though I had done the sanity tests [here](https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#sanity-tests) and everything seemed fine.

Thank you for your support. Have a nice day.

**Comment by diabonas** [comment]
> I do have such a TPM device under dev:
> ![image](https://user-images.githubusercontent.com/22464721/99047384-34c3a280-25a5-11eb-826b-de5d0ed1a0c5.png)

Your device files don't have the correct permissions: `/dev/tpm0` should be owned by `tss:root`, `/dev/tpmrm0` should be owned by `tss:tss`, both should have permissions `0660` (i.e. read-writable by the group as well). This prevents tpm2-abrmd from accessing the TPM as the `tss` user, leading to the depicted error message.

Which versions of tpm2-tss and tpm2-abrmd are you using, and how did you install them? tpm2-tss ships with [udev rules](https://github.com/tpm2-software/tpm2-tss/blob/master/dist/tpm-udev.rules) that set the correct permissions for the devices, they are installed to `/usr/lib/udev/rules.d/*tpm-udev.rules` by default.

> Alternatively I do this:
> `tpm_server &`
> `sudo -u tss tpm2-abrmd --tcti=mssim &`

This does something quite different: it starts a software TPM simulator and instructs tpm2-abrmd to use that instead of the real TPM device. It's fine for testing purposes if you don't have or don't want to use an actual TPM, please don't use it in production though.

BTW, since you have a recent enough kernel that features an in-kernel resource manager for the TPM (`/dev/tpmrm0`), you don't necessarily need tpm2-abrmd at all: after fixing the permissions issue described above, you can add your user to the `tss` group, which allows you to access the TPM with normal user rights, without having tpm2-abrmd installed.

**Comment by williamcroberts** [comment]
@heobu did the information @diabonas provide solve your issue?

**Comment by williamcroberts** [comment]
> @heobu did the information @diabonas provide solve your issue?

@heobu ping, did the fix work, can I close this?
