### ISSUE TITLE
make install reverts edits to /etc/dbus-1/system.d/tpm2-abrmd.conf

### ISSUE THREAD

**Issue by kgold2** [tpm2-software/tpm2-abrmd#773]
Evidently, an edit to that file is required to add a user to the abrmd dbus policy.

1. I don't see any official documentation.  In general, the entire DBUS area needs better documentation.
2. When I do a make install, it reverts my edits.  I don't know what the cleanest solution is, but at least back up my edited file.  Hand editing xml is fragile.

**Comment by williamcroberts** [comment]
Yeah because make install takes the local version and installs it, over the top, buy design.

You can edit the local version so when it does a make install it installs the version you want. That file would be `dist/tpm2-abrmd.conf`

The other option is to run the daemon as user tss or root. You need the option --allow-root to tpm2-abrmd to start and run as root. Something like `sudo -u tss tpm2-abrmd --tcti=mssim`

**Comment by tstruk** [comment]
As described in the INSTALL.md [1] it is recommended running the daemon as tss user.
The end user can of course modify the dbus config file and add whatever he wants, but the make install will overwrite the local changes. These kind of issues are best handled by tools like dpkg [2] or rpm [3].
It is not the job of nether autoconf or automake.
If one installs the code from source, one needs to take care of this issues her/him self.

[1] https://github.com/tpm2-software/tpm2-abrmd/blob/master/INSTALL.md#system-user--group
[2] https://debian-handbook.info/browse/wheezy/sect.package-meta-information.html#sidebar.questions-conffiles
[3] http://ftp.rpm.org/max-rpm/ch-rpm-upgrade.html (see the "Config file magic" section)
